const listData: ESObject = [
  {
    "title": "title1",
    "phone": "111xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容1",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title2",
    "phone": "222xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容2",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title3",
    "phone": "333xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容3",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title4",
    "phone": "444xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容4",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title5",
    "phone": "555xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容5",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title6",
    "phone": "666xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容6",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  },
  {
    "title": "title7",
    "phone": "777xxxx",
    "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容7",
    "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
  }
];

const listData222: ESObject = [
  { "title": "title11", "icon": "service/icon_baoxiu", "bgImg": "service/bg_service_baoxiu" }
];

const groupData: ESObject = [
  {
    "groupTitle": "groupTitle_1",
    "num": "22",
    "data": [
      {
        "title": "group1_title11",
        "phone": "111xxxx",
        "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容1",
        "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
      },
      {
        "title": "group1_title2",
        "phone": "222xxxx",
        "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容2",
        "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
      }
    ] as ESObject
  },
  {
    "groupTitle": "groupTitle_2",
    "num": "22",
    "data": [
      {
        "title": "group2_title33",
        "phone": "333xxxx",
        "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容3",
        "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
      },
      {
        "title": "group2_title44",
        "phone": "444xxxx",
        "content": "这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容这是内容4",
        "imageUrl": "https://gitee.com/iotjh/Picture/raw/master/lufei.png"
      }
    ] as ESObject
  }
];
